version: "3.8"
services:
  app:
    image: docker-nextjs-dev
    restart: unless-stopped
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./pages:/app/pages
      - ./styles:/app/styles
      - ./public:/app/public
