version: "3.8"
services:
  app:
    image: docker-nextjs-dev
    restart: unless-stopped
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./src/pages:/app/src/pages
      - ./src/styles:/app/src/styles
      - ./public:/app/public
